# Artificial Neural Network

### Importing the libraries

In [17]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [18]:
tf.__version__

'2.17.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [19]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [20]:
print(X)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


### Splitting the dataset into the Training set and Test set

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

###Feature Scaling
the third column has values around 1000, while the other columns have values less than 100. This large difference in scale can hinder the learning process of the neural network. Therefore, in this case, scaling is recommended.

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
sc_df = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [23]:
print(X_train)

[[-1.14 -0.89  0.67  0.52]
 [-0.81 -0.01  0.45  0.15]
 [ 1.77  1.85  0.24 -1.88]
 ...
 [-0.38 -1.25  0.85  0.13]
 [-0.92 -1.04  1.55  0.88]
 [ 1.7   1.06 -1.2  -2.42]]


## Part 2 - Building the ANN

### Initializing the ANN

In [24]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [25]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [27]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [28]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [29]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) # default batch size 32

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 205570.0156
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 194437.3125
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 153119.5938
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 89761.5156
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 45196.3867
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26406.1875
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 19117.0664
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 14746.3389
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10975.5547
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 7754.4883
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 4918.7969
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 3210.7971
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 2181.4639
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss:

### Predicting the results of the Test set

In [34]:
y_pred = ann.predict(X_test)
y_p = ann.predict(sc.transform([[5.3,40.4,1123.16,96.14]]))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
print(y_p)

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
[[431.53 431.23]
 [459.03 460.01]
 [463.23 461.14]
 ...
 [470.1  473.26]
 [442.95 438.  ]
 [462.57 463.28]]
[[560.66]]


Calculate mean_squared_error and R2 score

In [31]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred) # 1 - sum((y_pred - y_test)**2)/sum((y_pred - y_avg)**2)

print("MSE:", mse)
print("R-squared:", r2) # ~0.9 very good; < 0.7 - not great; < 0.4 - terrible; < 0 - not good at all

MSE: 19.979465110730033
R-squared: 0.9316912955493875
